services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/src
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/libpostgresql/data"
    env_file:
      config.env
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:8080"
    env_file:
      - config.env